# netlify.toml
[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  # Define los encabezados para las imágenes optimizadas y otros activos estáticos
  for = "/_next/static/media/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Añade más reglas de encabezados según sea necesario
